version: '3.8'

services:
  network-test:
    image: ghcr.io/mrgarbonzo/docker_test:latest
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: network-test